### ISSUE TITLE
Potential MIT License?

### ISSUE THREAD

**Issue by Allar** [Omnifinity/OpenVR-Tracking-Example#10]
Hi! I'd like to use your code but there currently isn't any form of licensing. Is there any chance you would consider a permissible license like MIT?

**Comment by mojodo** [comment]
Hi, thanks for asking. 

This repository is just a fork of the repository `https://github.com/Omnifinity` and does not contribute any new commits.
Therefore, the right people to ask are those mentioned in [https://github.com/Omnifinity]().

**Comment by peroht** [comment]
Hi Allar, 
thank you for your question.

How would e.g. BSD3 do for your intentions?

**Comment by dallinson** [comment]
Hello-I'd also like to use/modify some code from here, but have also run into the license issue-either MIT or BSD3 would be fine for what I need.
Thanks!

**Comment by peroht** [comment]
Hi, 
I am willing to go for Apache 2 on this, ok?

**Comment by peroht** [comment]
Hi @allar and @dallinson,
Added BSD3 license. Hope it helps. Closing.
