### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by piede828** [Omnifinity/OpenVR-Tracking-Example#2]
Getting following error:
`unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?	HTC Lighthouse Tracking Example	d:\openvr-tracking-example-master\openvr-tracking-example-master\htc lighthouse tracking example\lighthousetracking.cpp	445	`

**Comment by Sedowan** [comment]
In a console application: try to set it up without precompiled headers or include it manually.
I ran into the same issue but by interacting with other code bits.

**Comment by josephsipos** [comment]
@piede828 did you ever figure this out? I am getting the same error?

**Comment by peroht** [comment]
Did you guys figure this out on your end @piede828 @josephsipos

**Comment by peroht** [comment]
No reply. Closing.
