### ISSUE TITLE
Unable to compile..

### ISSUE THREAD

**Issue by markviews** [Omnifinity/OpenVR-Tracking-Example#3]
I am getting error LNK2019 when trying to compile, here are the steps I have taken:

1. Downloaded and extracted the source code
2. Downloaded openvr source code and extracted it to the "HTC Lighthouse Tracking Example" project folder
3. Copied openvr_api.dll from PlaySpaceMover to the "HTC Lighthouse Tracking Example" project folder
4. Changed line #6 of LightHouseTracking.h to #include "headers\openvr.h"
5. Disabled Precompiled Header in Properties > C/C+ > Precompiled Headers
![082646](https://user-images.githubusercontent.com/46404728/50810979-2c232680-12c1-11e9-9950-3ceff1b16a35.png)
Any help is much appreciated, I would love to get this working.

**Comment by Squad1Lieutenant** [comment]
I am getting the same errors as well. I have not found a fix to them either, but I will keep looking for a solution. Have you figured anything out?
I have also noticed, even with precompiled headers enabled, I still get the same errors.

**Comment by peroht** [comment]
> I am getting error LNK2019 when trying to compile, here are the steps I have taken:
> 
> 1. Downloaded and extracted the source code
> 2. Downloaded openvr source code and extracted it to the "HTC Lighthouse Tracking Example" project folder
> 3. Copied openvr_api.dll from PlaySpaceMover to the "HTC Lighthouse Tracking Example" project folder
> 4. Changed line #6 of LightHouseTracking.h to #include "headers\openvr.h"
> 5. Disabled Precompiled Header in Properties > C/C+ > Precompiled Headers
>    ![082646](https://user-images.githubusercontent.com/46404728/50810979-2c232680-12c1-11e9-9950-3ceff1b16a35.png)
>    Any help is much appreciated, I would love to get this working.

In this application, during build time, I link to the static library "openvr_api.lib". This is what is causing your compiler to protest.

First, if building with visual studio, and let say you build for win32, in the "Linker > General > Additional library directories" ensure that you have added the path to where your local openvr "lib\win32" folder sits on your hard drive.

Secondly in the "Linker > Input > Additional dependencies" ensure that you have added the "openvr_api.lib" library.

This should fix your linking error.

**Comment by markviews** [comment]
Awesome, I am able to successfully build the program, thank you!

But now when I run the project I get "Cannot find or open the PDB file" for three dll files.. I verified the dll files exsist, and ran Visual Code Studio as admin, but still got the errors..
![030808](https://user-images.githubusercontent.com/46404728/50864852-2af10880-1358-11e9-8e0a-14b52d2e72d0.png)

**Comment by markviews** [comment]
YESSS I got it working, I had 64 bit openvr_api.dll, and replace it with 32 bit one!

**Comment by peroht** [comment]
Great. Happy to help. Closing.
