### ISSUE TITLE
Get touchpad touch location?

### ISSUE THREAD

**Issue by markviews** [Omnifinity/OpenVR-Tracking-Example#4]
Is it possible to get the touch-pad touch location, or any data of where the touchpad is pressed?

**Comment by peroht** [comment]
You can find a way of doing this here:

https://github.com/Omnifinity/OpenVR-Tracking-Example/blob/master/HTC%20Lighthouse%20Tracking%20Example/LighthouseTracking.cpp#L487

**Comment by markviews** [comment]
awesome, thank you
